# Generated by Django 2.1.3 on 2018-11-17 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalStudentRegistrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_studentregistrations_last_updated', models.DateTimeField(auto_now=True, db_column='final_studentregistrations_last_updated')),
                ('final_studentregistrations_cid', models.ForeignKey(db_column='final_studentRegistrations_cid', on_delete=django.db.models.deletion.DO_NOTHING, to='users.Course')),
                ('final_studentregistrations_sid', models.ForeignKey(db_column='final_studentRegistrations_sid', on_delete=django.db.models.deletion.DO_NOTHING, to='users.Student')),
            ],
        ),
        migrations.AlterField(
            model_name='studentregistrations',
            name='studentregistrations_last_updated',
            field=models.DateTimeField(auto_now=True, db_column='studentregistrations_last_updated'),
        ),
    ]
