# Generated by Django 2.1.1 on 2018-11-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistrations',
            name='studentregistrations_id',
            field=models.AutoField(auto_created=True, db_column='studentRegistrations_id', primary_key=True, serialize=False),
        ),
    ]
