# Generated by Django 2.1.3 on 2018-12-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalstudentregistrations',
            name='final_student_first_name',
            field=models.CharField(db_column='final_student_first_name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='finalstudentregistrations',
            name='final_student_last_name',
            field=models.CharField(db_column='final_student_last_name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='finalstudentregistrations',
            name='final_student_middle_name',
            field=models.CharField(db_column='final_student_middle_name', max_length=100, null=True),
        ),
    ]
