# Generated by Django 2.1.3 on 2018-12-09 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_cid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Course')),
                ('audit_sid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Student')),
            ],
            options={
                'db_table': 'AuditCourse',
                'managed': True,
            },
        ),
    ]
