# Generated by Django 2.1.3 on 2018-11-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bufferspecialpermissionstable',
            name='req',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bufferspecialpermissionstable',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
