# Generated by Django 2.1.3 on 2018-11-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181115_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_max_students',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_prof',
            field=models.CharField(default='prof', max_length=45),
            preserve_default=False,
        ),
    ]
