# Generated by Django 2.1.3 on 2018-11-17 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181117_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalstudentregistrations',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='finalstudentregistrations',
            table='FinalStudentRegistrations',
        ),
    ]
