# Generated by Django 2.1.3 on 2018-12-09 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181209_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalstudentregistrations',
            name='final_student_first_name',
        ),
        migrations.RemoveField(
            model_name='finalstudentregistrations',
            name='final_student_last_name',
        ),
        migrations.RemoveField(
            model_name='finalstudentregistrations',
            name='final_student_middle_name',
        ),
    ]
