# Generated by Django 2.1.3 on 2018-11-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181115_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='delivery_mode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='description', max_length=250),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='pre_req',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='rigour',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
