# Generated by Django 2.1.1 on 2018-10-19 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181019_1459'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course_details',
            new_name='Details',
        ),
    ]
