# Generated by Django 2.1.3 on 2018-11-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181117_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_grade',
            field=models.CharField(db_column='Student_Grade', default='N', max_length=100),
            preserve_default=False,
        ),
    ]
