# Generated by Django 2.1.3 on 2018-11-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181115_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='description', max_length=250),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='prof',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='rigour',
            field=models.TextField(default=0, max_length=2),
        ),
    ]
