<<<<<<< HEAD
# Generated by Django 2.1.1 on 2018-10-25 14:07
=======
# Generated by Django 2.0.5 on 2018-10-25 11:11
>>>>>>> 649b8068a6a841a7d569ed94e35e41f9478d173d

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181019_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('name', models.CharField(max_length=30)),
                ('roll', models.CharField(max_length=12)),
                ('year', models.CharField(max_length=4)),
                ('email', models.CharField(max_length=20)),
=======
                ('student_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
>>>>>>> 649b8068a6a841a7d569ed94e35e41f9478d173d
            ],
        ),
    ]
