# Generated by Django 2.0.5 on 2018-10-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181019_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
