# Generated by Django 2.1.2 on 2018-10-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='course',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_point',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
