# Generated by Django 2.1.2 on 2018-10-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20181025_0529'),
        ('users', '0006_student'),
    ]

    operations = [
    ]
