# Generated by Django 2.0.5 on 2018-10-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20181025_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditcourse',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
