# Generated by Django 2.1.1 on 2018-10-25 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20181025_0529'),
        ('users', '0008_auto_20181025_1433'),
    ]

    operations = [
    ]
