# Generated by Django 2.1.1 on 2018-10-25 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20181025_1503'),
        ('users', '0010_student'),
        ('users', '0002_academiccourse'),
    ]

    operations = [
    ]
