# Generated by Django 2.1.1 on 2018-10-26 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_specialpermissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BufferSpecialPermissionsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req', models.CharField(max_length=20)),
                ('status', models.CharField(default='pending', max_length=4)),
                ('email', models.CharField(max_length=30)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Course')),
            ],
        ),
    ]
