# Generated by Django 2.1.1 on 2018-10-27 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_final_register'),
        ('users', '0013_bufferspecialpermissionstable'),
    ]

    operations = [
    ]
